### PR TITLE
detector: emit a "node up" event for newly registered connected nodes

### PR DESCRIPTION
**Pull request by shun159**
See #21, #23. References #13.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@shun159 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/aten&pullRequestId=22)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/aten&pullRequestId=22) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@shun159 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/aten&pullRequestId=22)!

**Comment by michaelklishin** [comment]
@kjnilsson this looks reasonable to me and all existing tests pass. Are there any reasons why a `down` event should be emitted for newly registered connected nodes?

**Comment by michaelklishin** [comment]
It's a good question whether the event we emit for newly registered nodes should be consistent. We could try connecting to the node and emitting a "node up" event after the fact. @shun159 how does that sound?

**Comment by dcorbacho** [comment]
I can't think any reason why the `down` event should be emitted, given that we can detect the node as up and emit an `up` event. If after registering we couldn't connect, a `down` would be appropiate.

**Comment by shun159** [comment]
@michaelklishin

That sounds good,  more reasonable.
How is this commit(4ce2a45)?

**Comment by michaelklishin** [comment]
This looks reasonable. Let's wait for @kjnilsson's opinion next week.

**Comment by michaelklishin** [comment]
FTR, https://github.com/rabbitmq/aten/commit/e7b76746925ff0b1272b86668dd8b16fbf2ef668 explains the above change (https://github.com/rabbitmq/aten/pull/22/commits/ee77b4fa118495948aac7f609de3639c2a6d1b6e).

**Comment by kjnilsson** [comment]
Hi,

After thinking about this for a while and doing some testing I think `aten` works exactly as expected. Aten _only_ operates on aten heartbeats. Whether a node is connected or not is irrelevant to the aten detector. The only thing that matters and should matter is whether the node in question has emitted heartbeats and how long ago it's last heartbeat was emitted.

Taking the above into account it is perfectly reasonable for a connected node to be considered down if no heartbeats have been received as would be the case for a very newly  connected node or a node that hasn't got aten running on it. 

I think it would be unhelpful and difficult to try to merge the erlang node connected state with the inferred state calculated by aten.

I'm closing this for now. If you can provide a scenario for me to test that you still consider wrong I am more than happy to re-open this.

Thanks very much. :)

**Comment by shun159** [comment]
@kjnilsson 

I understand your comment,
thank you very much for the review!

**Comment by kjnilsson** [comment]
@shun159 to elaborate a little more - aten only really provides hints of the current state (mostly to get a timely hint of a network partition). The actions you take based on these hints should not be disruptive to your system as during normal operation it is very possible to get a `down` then very shortly after and `up` if the distribution port is a bit clogged or the network has a short blip.

A common thing to do would be to set a timer on receiving a `down` notification that is longer than the aten poll interval _then_ taking some action that may change state or move processes or other.

In `ra` (who uses `aten`) the aten down notification is used to start a pre vote process which is the first phase of electing a new leader. This is safe and not disruptive.

Hope this clarifies the use case of aten somewhat. :)

**Pull request closed without merging**
